
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action SaveAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action LastProjectsAction;

	private global::Gtk.Action ManageProjectsAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.Notebook tabsControl;

	private global::Gtk.VPaned qlSplitter;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView qlEditor;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView qlResultGrid;

	private global::Gtk.Label tabLableQL;

	private global::Gtk.Label tabLabelTView;

	private global::Gtk.Statusbar statusbar;

	private global::Gtk.Image busyIcon;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.LastProjectsAction = new global::Gtk.Action ("LastProjectsAction", global::Mono.Unix.Catalog.GetString ("Last projects"), null, null);
		this.LastProjectsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Last projects");
		w1.Add (this.LastProjectsAction, null);
		this.ManageProjectsAction = new global::Gtk.Action ("ManageProjectsAction", global::Mono.Unix.Catalog.GetString ("Manage projects..."), null, null);
		this.ManageProjectsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Manage projects...");
		w1.Add (this.ManageProjectsAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("CodeQL");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='SaveAction' action='SaveAction'/><menu name='LastProjectsAction' action='LastProjectsAction'/><menuitem name='ManageProjectsAction' action='ManageProjectsAction'/><separator/><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.tabsControl = new global::Gtk.Notebook ();
		this.tabsControl.CanFocus = true;
		this.tabsControl.Name = "tabsControl";
		this.tabsControl.CurrentPage = 1;
		// Container child tabsControl.Gtk.Notebook+NotebookChild
		this.qlSplitter = new global::Gtk.VPaned ();
		this.qlSplitter.CanFocus = true;
		this.qlSplitter.Name = "qlSplitter";
		this.qlSplitter.Position = 112;
		// Container child qlSplitter.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.qlEditor = new global::Gtk.TextView ();
		this.qlEditor.CanFocus = true;
		this.qlEditor.Name = "qlEditor";
		this.GtkScrolledWindow.Add (this.qlEditor);
		this.qlSplitter.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.qlSplitter[this.GtkScrolledWindow]));
		w4.Resize = false;
		// Container child qlSplitter.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.qlResultGrid = new global::Gtk.TreeView ();
		this.qlResultGrid.CanFocus = true;
		this.qlResultGrid.Name = "qlResultGrid";
		this.GtkScrolledWindow1.Add (this.qlResultGrid);
		this.qlSplitter.Add (this.GtkScrolledWindow1);
		this.tabsControl.Add (this.qlSplitter);
		// Notebook tab
		this.tabLableQL = new global::Gtk.Label ();
		this.tabLableQL.Name = "tabLableQL";
		this.tabLableQL.LabelProp = global::Mono.Unix.Catalog.GetString ("QL");
		this.tabsControl.SetTabLabel (this.qlSplitter, this.tabLableQL);
		this.tabLableQL.ShowAll ();
		// Notebook tab
		global::Gtk.Label w8 = new global::Gtk.Label ();
		w8.Visible = true;
		this.tabsControl.Add (w8);
		this.tabLabelTView = new global::Gtk.Label ();
		this.tabLabelTView.Name = "tabLabelTView";
		this.tabLabelTView.LabelProp = global::Mono.Unix.Catalog.GetString ("TView");
		this.tabsControl.SetTabLabel (w8, this.tabLabelTView);
		this.tabLabelTView.ShowAll ();
		this.vbox1.Add (this.tabsControl);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.tabsControl]));
		w9.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		// Container child statusbar.Gtk.Box+BoxChild
		this.busyIcon = new global::Gtk.Image ();
		this.busyIcon.Name = "busyIcon";
		this.busyIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
		this.statusbar.Add (this.busyIcon);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.statusbar[this.busyIcon]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.statusbar);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 647;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnExitActionActivated);
	}
}
