// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action LoadAction;
    
    private Gtk.Action SaveAction;
    
    private Gtk.Action ExitAction;
    
    private Gtk.Action LastProjectsAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar2;
    
    private Gtk.DrawingArea drawingarea1;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.LoadAction = new Gtk.Action("LoadAction", Mono.Unix.Catalog.GetString("Load"), null, "gtk-open");
        this.LoadAction.ShortLabel = Mono.Unix.Catalog.GetString("Load");
        w1.Add(this.LoadAction, null);
        this.SaveAction = new Gtk.Action("SaveAction", Mono.Unix.Catalog.GetString("Save"), null, "gtk-save");
        this.SaveAction.ShortLabel = Mono.Unix.Catalog.GetString("Save");
        w1.Add(this.SaveAction, null);
        this.ExitAction = new Gtk.Action("ExitAction", Mono.Unix.Catalog.GetString("Exit"), null, "gtk-quit");
        this.ExitAction.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w1.Add(this.ExitAction, null);
        this.LastProjectsAction = new Gtk.Action("LastProjectsAction", Mono.Unix.Catalog.GetString("Last projects"), null, null);
        this.LastProjectsAction.ShortLabel = Mono.Unix.Catalog.GetString("Last projects");
        w1.Add(this.LastProjectsAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("CodeQL");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-execute", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='LoadAction' action='LoadAction'/><menuitem name='SaveAction' action='SaveAction'/><menu name='LastProjectsAction' action='LastProjectsAction'/><separator/><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
        this.menubar2 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
        this.menubar2.Name = "menubar2";
        this.vbox1.Add(this.menubar2);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.drawingarea1 = new Gtk.DrawingArea();
        this.drawingarea1.Name = "drawingarea1";
        this.vbox1.Add(this.drawingarea1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.drawingarea1]));
        w3.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w4.PackType = ((Gtk.PackType)(1));
        w4.Position = 2;
        w4.Expand = false;
        w4.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 647;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.LoadAction.Activated += new System.EventHandler(this.OnLoadActionActivated);
        this.ExitAction.Activated += new System.EventHandler(this.OnExitActionActivated);
    }
}
