// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action SaveAction;
    
    private Gtk.Action ExitAction;
    
    private Gtk.Action LastProjectsAction;
    
    private Gtk.Action ManageProjectsAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar2;
    
    private Gtk.Notebook tabsControl;
    
    private Gtk.VPaned qlSplitter;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TextView qlEditor;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.TreeView qlResultGrid;
    
    private Gtk.Label tabLableQL;
    
    private Gtk.Label tabLabelTView;
    
    private Gtk.Statusbar statusbar;
    
    private Gtk.Image busyIcon;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.SaveAction = new Gtk.Action("SaveAction", Mono.Unix.Catalog.GetString("Save"), null, "gtk-save");
        this.SaveAction.ShortLabel = Mono.Unix.Catalog.GetString("Save");
        w1.Add(this.SaveAction, null);
        this.ExitAction = new Gtk.Action("ExitAction", Mono.Unix.Catalog.GetString("Exit"), null, "gtk-quit");
        this.ExitAction.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w1.Add(this.ExitAction, null);
        this.LastProjectsAction = new Gtk.Action("LastProjectsAction", Mono.Unix.Catalog.GetString("Last projects"), null, null);
        this.LastProjectsAction.ShortLabel = Mono.Unix.Catalog.GetString("Last projects");
        w1.Add(this.LastProjectsAction, null);
        this.ManageProjectsAction = new Gtk.Action("ManageProjectsAction", Mono.Unix.Catalog.GetString("Manage projects..."), null, null);
        this.ManageProjectsAction.ShortLabel = Mono.Unix.Catalog.GetString("Manage projects...");
        w1.Add(this.ManageProjectsAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("CodeQL");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-execute", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='SaveAction' action='SaveAction'/><menu name='LastProjectsAction' action='LastProjectsAction'/><menuitem name='ManageProjectsAction' action='ManageProjectsAction'/><separator/><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
        this.menubar2 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
        this.menubar2.Name = "menubar2";
        this.vbox1.Add(this.menubar2);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.tabsControl = new Gtk.Notebook();
        this.tabsControl.CanFocus = true;
        this.tabsControl.Name = "tabsControl";
        this.tabsControl.CurrentPage = 1;
        // Container child tabsControl.Gtk.Notebook+NotebookChild
        this.qlSplitter = new Gtk.VPaned();
        this.qlSplitter.CanFocus = true;
        this.qlSplitter.Name = "qlSplitter";
        this.qlSplitter.Position = 112;
        // Container child qlSplitter.Gtk.Paned+PanedChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.qlEditor = new Gtk.TextView();
        this.qlEditor.CanFocus = true;
        this.qlEditor.Name = "qlEditor";
        this.GtkScrolledWindow.Add(this.qlEditor);
        this.qlSplitter.Add(this.GtkScrolledWindow);
        Gtk.Paned.PanedChild w4 = ((Gtk.Paned.PanedChild)(this.qlSplitter[this.GtkScrolledWindow]));
        w4.Resize = false;
        // Container child qlSplitter.Gtk.Paned+PanedChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.qlResultGrid = new Gtk.TreeView();
        this.qlResultGrid.CanFocus = true;
        this.qlResultGrid.Name = "qlResultGrid";
        this.GtkScrolledWindow1.Add(this.qlResultGrid);
        this.qlSplitter.Add(this.GtkScrolledWindow1);
        this.tabsControl.Add(this.qlSplitter);
        // Notebook tab
        this.tabLableQL = new Gtk.Label();
        this.tabLableQL.Name = "tabLableQL";
        this.tabLableQL.LabelProp = Mono.Unix.Catalog.GetString("QL");
        this.tabsControl.SetTabLabel(this.qlSplitter, this.tabLableQL);
        this.tabLableQL.ShowAll();
        // Notebook tab
        Gtk.Label w8 = new Gtk.Label();
        w8.Visible = true;
        this.tabsControl.Add(w8);
        this.tabLabelTView = new Gtk.Label();
        this.tabLabelTView.Name = "tabLabelTView";
        this.tabLabelTView.LabelProp = Mono.Unix.Catalog.GetString("TView");
        this.tabsControl.SetTabLabel(w8, this.tabLabelTView);
        this.tabLabelTView.ShowAll();
        this.vbox1.Add(this.tabsControl);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.tabsControl]));
        w9.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar = new Gtk.Statusbar();
        this.statusbar.Name = "statusbar";
        this.statusbar.Spacing = 6;
        // Container child statusbar.Gtk.Box+BoxChild
        this.busyIcon = new Gtk.Image();
        this.busyIcon.Name = "busyIcon";
        this.busyIcon.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", Gtk.IconSize.Menu, 16);
        this.statusbar.Add(this.busyIcon);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.statusbar[this.busyIcon]));
        w10.Position = 2;
        w10.Expand = false;
        w10.Fill = false;
        this.vbox1.Add(this.statusbar);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar]));
        w11.PackType = ((Gtk.PackType)(1));
        w11.Position = 2;
        w11.Expand = false;
        w11.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 647;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.ExitAction.Activated += new System.EventHandler(this.OnExitActionActivated);
    }
}
